//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuditManager.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add entry to database.
        /// </summary>
        internal static string AddEntryFailed {
            get {
                return ResourceManager.GetString("AddEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added entry to database.
        /// </summary>
        internal static string AddEntrySuccess {
            get {
                return ResourceManager.GetString("AddEntrySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to archive database.
        /// </summary>
        internal static string ArchiveDatabaseFailed {
            get {
                return ResourceManager.GetString("ArchiveDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database archived successfully.
        /// </summary>
        internal static string ArchiveDatabaseSuccess {
            get {
                return ResourceManager.GetString("ArchiveDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed authentification.
        /// </summary>
        internal static string AuthentificationFailed {
            get {
                return ResourceManager.GetString("AuthentificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully authentificated.
        /// </summary>
        internal static string AuthentificationSuccess {
            get {
                return ResourceManager.GetString("AuthentificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to access {1}. Reason: {2}.
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully accessed to {1}.
        /// </summary>
        internal static string AuthorizationSuccess {
            get {
                return ResourceManager.GetString("AuthorizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create database.
        /// </summary>
        internal static string CreateDatabaseFailed {
            get {
                return ResourceManager.GetString("CreateDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database created successfully.
        /// </summary>
        internal static string CreateDatabaseSuccess {
            get {
                return ResourceManager.GetString("CreateDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete database.
        /// </summary>
        internal static string DeleteDatabaseFailed {
            get {
                return ResourceManager.GetString("DeleteDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database deleted successfully.
        /// </summary>
        internal static string DeleteDatabaseSuccess {
            get {
                return ResourceManager.GetString("DeleteDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to modify entry.
        /// </summary>
        internal static string ModifyEntryFailed {
            get {
                return ResourceManager.GetString("ModifyEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly modified entry.
        /// </summary>
        internal static string ModifyEntrySuccess {
            get {
                return ResourceManager.GetString("ModifyEntrySuccess", resourceCulture);
            }
        }
    }
}
